version: '3.1'
#
services:
#    
  db:
    image: fametec/bacula-catalog:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    # volumes:
    #   - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
#
  bacula-dir:
    image: fametec/bacula-director:latest
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    depends_on: 
      - db      
    ports:
      - 9101:9101
#
  bacula-sd:
    image: fametec/bacula-storage:latest
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9103:9103
#
  bacula-fd:
    image: fametec/bacula-client:latest
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - 9102:9102
#
  baculum:
    image: fametec/baculum:latest
    restart: unless-stopped
    depends_on: 
      - db
      - bacula-dir
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
    ports:
      - 9095:9095
      - 9096:9096
# 
#volumes: 
#  pgdata:
